//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCompany.ModelFirst
{
    using System;
    
    public enum OrderSource : int
    {
        Online = 1,
        Email = 2,
        Telephone = 3,
        Mail = 4,
        InPerson = 5
    }
}
